/* Define to prevent recursive inclusion */
#ifndef _USER_BLE_SERVICE_H_
#define _USER_BLE_SERVICE_H_

#ifdef __cplusplus
extern "C"  {
#endif      /* __cplusplus */

/* Add Includes here */
#include <profile_server.h>

/** @defgroup USER_UUIDs USER UUIDs
  * @brief USER BLE Profile UUID definitions
  * @{
  */
#define GATT_UUID_USER_PROFILE                    0xA55A
#define GATT_UUID_CHAR_USER_V1_READ               0xB001
#define GATT_UUID_CHAR_USER_V2_WRITE              0xB002
#define GATT_UUID_CHAR_USER_V3_NOTIFY             0xB003
#define GATT_UUID_CHAR_USER_V4_INDICATE           0xB004

/** @defgroup USER_Service USER Ble Service
  * @brief USER BLE service
  * @{
  */
/*============================================================================*
 *                              Macros
 *============================================================================*/
/** @defgroup USER_Service_Exported_Macros USER Service Exported Macros
  * @brief
  * @{
  */

/** @defgroup USER_Service_Application_Parameters USER Service Application Parameters
  * @brief  Type of parameters set/got from application.
  * @{
  */
typedef enum
{
    USER_BLE_SERVICE_PARAM_V1_READ_CHAR_VAL = 0x01,
} T_USER_PARAM_TYPE;

/** @} */



/** @defgroup USER_Service_Upstream_Message USER Service Upstream Message
  * @brief  Upstream message used to inform application.
  * @{
  */

/** @defgroup USER_Service_Read_Info USER Service Read Info
  * @brief  Parameter for reading characteristic value.
  * @{
  */
#define USER_READ_V1                                        1
/** @} */

/** @defgroup USER_Service_Write_Info USER Service Write Info
  * @brief  Parameter for writing characteristic value.
  * @{
  */
#define USER_WRITE_V2                                       1

/** @} */

/** @defgroup USER_Service_Notify_Indicate_Info USER Service Notify Indicate Info
  * @brief  Parameter for enable or disable notification or indication.
  * @{
  */
#define USER_NOTIFY_INDICATE_V3_ENABLE     1
#define USER_NOTIFY_INDICATE_V3_DISABLE    2
#define USER_NOTIFY_INDICATE_V4_ENABLE     3
#define USER_NOTIFY_INDICATE_V4_DISABLE    4


/** @} */

#define USER_READ_V1_MAX_LEN               300

/** @} End of USER_Service_Upstream_Message */



/** @} End of USER_Service_Exported_Macros */
/*============================================================================*
 *                              Types
 *============================================================================*/
/** @defgroup USER_Service_Exported_Types USER Service Exported Types
  * @brief
  * @{
  */

/** @defgroup TUSER_WRITE_MSG TUSER_WRITE_MSG
  * @brief USER BLE service written msg to application.
  * @{
  */
typedef struct
{
    uint8_t opcode; //!< ref:  @ref USER_Service_Write_Info
    T_WRITE_TYPE write_type;
    uint16_t len;
    uint8_t *p_value;
} TUSER_WRITE_MSG;
/** @} End of TUSER_WRITE_MSG */


/** @defgroup TUSER_UPSTREAM_MSG_DATA TUSER_UPSTREAM_MSG_DATA
  * @brief USER BLE service callback message content.
  * @{
  */
typedef union
{
    uint8_t notification_indification_index; //!< ref: @ref USER_Service_Notify_Indicate_Info
    uint8_t read_value_index; //!< ref: @ref USER_Service_Read_Info
    TUSER_WRITE_MSG write;
} TUSER_UPSTREAM_MSG_DATA;
/** @} End of TUSER_UPSTREAM_MSG_DATA */

/** @defgroup TUSER_CALLBACK_DATA TUSER_CALLBACK_DATA
  * @brief USER BLE service data to inform application.
  * @{
  */
typedef struct
{
    uint8_t                 conn_id;
    T_SERVICE_CALLBACK_TYPE msg_type;
    TUSER_UPSTREAM_MSG_DATA msg_data;
} TUSER_CALLBACK_DATA;
/** @} End of TUSER_CALLBACK_DATA */

/** @} End of USER_Service_Exported_Types */
/*============================================================================*
 *                              Functions
 *============================================================================*/
/** @defgroup USER_Service_Exported_Functions USER Service Exported Functions
  * @brief
  * @{
  */

/**
  * @brief Add USER BLE service to the BLE stack database.
  *
  * @param[in]   p_func  Callback when service attribute was read, write or cccd update.
  * @return Service id generated by the BLE stack: @ref T_SERVER_ID.
  * @retval 0xFF Operation failure.
  * @retval others Service id assigned by stack.
  *
  */
T_SERVER_ID user_ble_service_add_service(void *p_func);

/**
  * @brief  Set service related data from application.
  *
  * @param[in] param_type            parameter type to set.
  * @param[in] len                   value length to be set.
  * @param[in] p_value             value to set.
  * @return parameter set result.
  * @retval 0 false
  * @retval 1 true
  */
bool user_ble_service_set_parameter(T_USER_PARAM_TYPE param_type, uint16_t len, void *p_value);

/**
  * @brief send notification of USER notify characteristic value.
  *
  * @param[in] conn_id           connection id
  * @param[in] service_id        service ID of service.
  * @param[in] p_value           characteristic value to notify
  * @param[in] length            characteristic value length to notify
  * @return notification action result
  * @retval 1 true
  * @retval 0 false
  */
bool user_ble_service_send_v3_notify(uint8_t conn_id, T_SERVER_ID service_id,
                                     void *p_value, uint16_t length);
/**
  * @brief send indication of USER indicate characteristic value.
  *
  * @param[in] conn_id           connection id
  * @param[in] service_id        service ID of service.
  * @param[in] p_value           characteristic value to notify
  * @param[in] length            characteristic value length to notify
  * @return notification action result
  * @retval 1 true
  * @retval 0 false
  */
bool user_ble_service_send_v4_indicate(uint8_t conn_id, T_SERVER_ID service_id,
                                       void *p_value, uint16_t length);

/** @} End of USER_Service_Exported_Functions */

/** @} End of USER_Service */


#ifdef __cplusplus
}
#endif

#endif /* _USER_BLE_SERVICE_H_ */
